package com.mybatis.mapper;

import com.mybatis.models.Abc;
import com.mybatis.models.AbcExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AbcMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table abc
     *
     * @mbggenerated Sat Oct 24 20:57:50 CST 2015
     */
    int countByExample(AbcExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table abc
     *
     * @mbggenerated Sat Oct 24 20:57:50 CST 2015
     */
    int deleteByExample(AbcExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table abc
     *
     * @mbggenerated Sat Oct 24 20:57:50 CST 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table abc
     *
     * @mbggenerated Sat Oct 24 20:57:50 CST 2015
     */
    int insert(Abc record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table abc
     *
     * @mbggenerated Sat Oct 24 20:57:50 CST 2015
     */
    int insertSelective(Abc record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table abc
     *
     * @mbggenerated Sat Oct 24 20:57:50 CST 2015
     */
    List<Abc> selectByExample(AbcExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table abc
     *
     * @mbggenerated Sat Oct 24 20:57:50 CST 2015
     */
    int updateByExampleSelective(@Param("record") Abc record, @Param("example") AbcExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table abc
     *
     * @mbggenerated Sat Oct 24 20:57:50 CST 2015
     */
    int updateByExample(@Param("record") Abc record, @Param("example") AbcExample example);
}