package com.mybatis.models;

public class Abc {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column abc.id
     *
     * @mbggenerated Sat Oct 24 20:57:50 CST 2015
     */
    private Integer id;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column abc.id
     *
     * @return the value of abc.id
     *
     * @mbggenerated Sat Oct 24 20:57:50 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column abc.id
     *
     * @param id the value for abc.id
     *
     * @mbggenerated Sat Oct 24 20:57:50 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }
}